# Generated by Django 4.1.7 on 2023-05-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_post_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='blogimg/'),
        ),
    ]
